---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - {
        role: firewall,
        become: yes
      }
    - {
        role: filebeat,
        become: yes
      }
    - {
        role: openssh,
        become: yes
      }
